### ISSUE TITLE
Installation fails on a clean setup

### ISSUE THREAD

**Issue by pandy06269** [pandy06269/blue-twilight#17]
When installing a new instance of Blue Twilight, the app displays the "whoops" error message with the following error stack-trace:

```
Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'blue_twilight'@'localhost' (using password: NO) (SQL: select * from `configuration` where `key` = theme limit 1) in /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:770
Stack trace:
#0 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(351): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1648): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1634): Illuminate\Database\Query\Builder->runSelect()
#4 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(638): Illuminate\Database\Query\Builder->get(Array)
#5 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(327): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(297): Illuminate\Database\Eloquent\Builder->get(Array)
#7 /srv/www/blue-twilight-dev/app/Helpers/ConfigHelper.php(117): Illuminate\Database\Eloquent\Builder->first()
#8 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): App\Helpers\ConfigHelper->get('theme')
#9 /srv/www/blue-twilight-dev/app/Helpers/ThemeHelper.php(99): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#10 /srv/www/blue-twilight-dev/app/Helpers/ThemeHelper.php(61): App\Helpers\ThemeHelper->getThemeName()
#11 /srv/www/blue-twilight-dev/app/Providers/AppServiceProvider.php(51): App\Helpers\ThemeHelper->viewName('partials.pager_...')
#12 [internal function]: App\Providers\AppServiceProvider->boot()
#13 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#14 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\Container\Container->call(Array)
#15 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(752): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\AppServiceProvider))
#16 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider), 12)
#17 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(753): array_walk(Array, Object(Closure))
#18 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#19 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#20 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(254): Illuminate\Foundation\Application->bootstrapWith(Array)
#21 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Foundation\Http\Kernel->bootstrap()
#22 /srv/www/blue-twilight-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /srv/www/blue-twilight-dev/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}
```

**Comment by pandy06269** [comment]
This was due to trying to read a config setting prior to install.
